#dist: xenial
git:
  quiet: true
  depth: false
notifications:
  email: false
language: java
jdk: openjdk8
python: 3.7
install: true
addons:
  apt:
    update: true
    packages:
      #- sudo
      #- lsof
      #- wget
      #- bash
      - curl
      #- python3-dev
      - python3-pip
      #- python3-six
      #- python3-setuptools
os: linux
arch: amd64
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip setuptools
  - pip install --user --upgrade httpie
  - source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
  - stop_any 5432 5672 27017 8080 8000 8081 80 80
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: test openjdk8
      script: cd $TRAVIS_BUILD_DIR/ && ./sbtw clean "runMain com.github.daggerok.akka.persistence.PersistentActorExample" clean "runMain com.github.daggerok.akka.persistence.PersistentActorFailureExample" clean "runMain com.github.daggerok.akka.persistence.SnapshotExample"
    - stage: test
      jdk: openjdk11
      name: test openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/
        - ./sbtw clean "runMain com.github.daggerok.akka.persistence.PersistentActorExample"
                 clean "runMain com.github.daggerok.akka.persistence.PersistentActorFailureExample"
                 clean "runMain com.github.daggerok.akka.persistence.SnapshotExample"
        - cat target/persistence-snapshots/snapshot-*
cache:
  directories:
    - "~/.ivy"
    - "~/.sbt"
  pip: true
  packages: true
